### PR TITLE
Ansible User-Agent identification

### PR DESCRIPTION
**Pull request by abikouo**
##### SUMMARY

Ansible User-Agent identification

##### ISSUE TYPE

- Feature Pull Request

### CODE REVIEW

**Comment by alinabuzachis** [comment]
@goneri @GomathiselviS gouttelette has broken the amazon_cloud_code_generator. 

One of the issues is this function:
```
def get_generator() -> Dict[str, Any]:
    generator = {}

    with open("gouttelette.yml", "r") as file:
        try:
            generator.update({"name": yaml.safe_load(file)["generator"]})
            if "amazon_cloud_code_generator" in generator["name"]:
                generator.update({"default_path": "cloud"})
            elif "vmware_rest_code_generator" in generator["name"]:
                generator.update({"default_path": "vmware_rest"})
        except yaml.YAMLError as exc:
            print(exc)
    return generator
```

If I run tox -e refresh_modules against the amazon_cloud_code_generator, the function tries to open `gouttelette.yml` that's not part of the amazon_cloud_code_generator folder.

It also requires this PR https://github.com/ansible-collections/amazon_cloud_code_generator/pull/61

**Comment by GomathiselviS** [comment]
> @goneri @GomathiselviS gouttelette has broken the amazon_cloud_code_generator.
> 
> One of the issues is this function:
> 
> ```
> def get_generator() -> Dict[str, Any]:
>     generator = {}
> 
>     with open("gouttelette.yml", "r") as file:
>         try:
>             generator.update({"name": yaml.safe_load(file)["generator"]})
>             if "amazon_cloud_code_generator" in generator["name"]:
>                 generator.update({"default_path": "cloud"})
>             elif "vmware_rest_code_generator" in generator["name"]:
>                 generator.update({"default_path": "vmware_rest"})
>         except yaml.YAMLError as exc:
>             print(exc)
>     return generator
> ```
> 
> If I run tox -e refresh_modules against the amazon_cloud_code_generator, the function tries to open `gouttelette.yml` that's not part of the amazon_cloud_code_generator folder.
> 
> It also requires this PR #61

@alinabuzachis I will work on fixing this issue. 
@abikouo @alinabuzachis Shouldn't this PR be on amazon.cloud collection?

**Comment by alinabuzachis** [comment]
@GomathiselviS Not sure how it works when https://github.com/ansible-collections/amazon_cloud_code_generator/pull/62 is merged. Do you still handle copying data/ content to cloud folder while generating collection?

**Comment by GomathiselviS** [comment]
> @GomathiselviS Not sure how it works when #62 is merged. Do you still handle copying data/ content to cloud folder while generating collection?

Yes, I have not removed the copying of data folder yet. But I prefer to remove it , if we agree upon deleting these files from the generator.

**Comment by alinabuzachis** [comment]
@GomathiselviS Ok, so let's keep as to is for the moment and we can merge Aubin's PR directly here. We can remove the part copying over the data folder before archiving this repo.

**Comment by GomathiselviS** [comment]
> @GomathiselviS Ok, so let's keep as to is for the moment and we can merge Aubin's PR directly here. We can remove the part copying over the data folder before archiving this repo.

@alinabuzachis With [PR](https://github.com/ansible-collections/amazon_cloud_code_generator/pull/62), all the work of code generation will be done by gouttelette. We do not need a separate gouttelette or amazon_cloud_code_generator folder in the amazon_cloud_code_generator repo anymore. gouttelette does not have the module_utils files for the reasons mentioned above. This PR should either be against amazon.cloud or gouttelette (with the module_utils files added back).

**Comment by alinabuzachis** [comment]
recheck

**Comment by alinabuzachis** [comment]
@abikouo Cn you please rebase your PR?

**Comment by abikouo** [comment]
> @abikouo Can you please rebase your PR?

please see comment above

**Pull request closed without merging**
