### PR TITLE
Use jinja2_renderer from gouttelette.utils

### PR DESCRIPTION
**Pull request by goneri**
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1715

### CODE REVIEW

**Review by alinabuzachis — APPROVED** [review]

**Comment by alinabuzachis** [comment]
@goneri is it ready to be merged?

**Comment by goneri** [comment]
Not yet. Thanks for asking.

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by GomathiselviS** [comment]
recheck

**Review by alinabuzachis — COMMENTED** [review]
I do not think we need cloud folder in this PR.

**Pull request merged**
